// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PawCast.Infrastructure.Persistence;

#nullable disable

namespace PawCast.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PawCastDbContext))]
    [Migration("20260313034924_AddForecastSnapshotsAndWalkIndexResults")]
    partial class AddForecastSnapshotsAndWalkIndexResults
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PawCast.Domain.Entities.FetchRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at_utc");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("fetch_runs", (string)null);
                });

            modelBuilder.Entity("PawCast.Domain.Entities.ForecastSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("FetchedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at_utc");

                    b.Property<DateTimeOffset>("ForecastTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("forecast_time_utc");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("RawAirQualityJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_air_quality_json");

                    b.Property<string>("RawWeatherJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_weather_json");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("Latitude", "Longitude", "ForecastTimeUtc");

                    b.ToTable("forecast_snapshots", (string)null);
                });

            modelBuilder.Entity("PawCast.Domain.Entities.WalkIndexResultRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ForecastTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("forecast_time_utc");

                    b.Property<DateTimeOffset>("GeneratedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at_utc");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("grade");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<decimal>("Pm25")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("pm25");

                    b.Property<int>("PrecipitationProbability")
                        .HasColumnType("integer")
                        .HasColumnName("precipitation_probability");

                    b.Property<string>("ReasonsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("reasons_json");

                    b.Property<decimal>("TemperatureC")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("temperature_c");

                    b.Property<decimal>("UvIndex")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("uv_index");

                    b.Property<int>("WalkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("walk_index");

                    b.Property<decimal>("WindKph")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("wind_kph");

                    b.HasKey("Id");

                    b.HasIndex("Latitude", "Longitude", "ForecastTimeUtc")
                        .IsUnique();

                    b.ToTable("walk_index_results", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
